import SwiftUI

struct Decade: Identifiable {
    let id: String
    let title: String
    let subtitles: [String]
    let imageNames: [String]
    let descriptions: [String]
}

let decades = [
    Decade(id: "1960s", title: "Birth of a Nation", subtitles: ["Independence", "Race Riots", "1st Terrorist Attack"], imageNames: ["SingaporeSeperation", "SGRaceRiots", "SGTerroristAttack"], descriptions: ["After merging with Malaysia in 1963, Singapore was expelled in 1965 due to tensions and political reasons, forcing it to become independent.", "Fueled by political tensions, race riots erupted across Singapore in 1964, leading to casualties and damaging the interacial relations.", "Singapore faced its first international terrorist attack in the 1960s, a politically motivated bombing of the MacDonald House which killed 3, highlighting the need for enhanced security measures."]),
    Decade(id: "1970s", title: "Nation Building", subtitles: ["Economic Transformation", "1st Chingay Parade"], imageNames: ["SGEcoProgress", "SGChingay"], descriptions: ["Singapore pursued aggressive economic growth through export manufacturing and trade, establishing itself as a global trading hub.", "The Chingay Parade was introduced in 1973 to celebrate Chinese New Year, as a street parade. The bright colours and vibrancy helped compensate for the recent ban on firecrackers."]),
    Decade(id: "1980s", title: "Developing Infrastructure", subtitles: ["Changi Airport Opening", "Establishing the MRT"], imageNames: ["SGChangi", "SGMRT"], descriptions: ["Singapore Changi Airport commenced operations in 1981, serving as a pivotal hub for international air travel and bolstering the nation's status as a global connectivity center.", "The Mass Rapid Transport System was established in 1987, revolutionizing public transportation while providing efficient and reliable connectivity."]),
    Decade(id: "1990s", title: "Growing Further", subtitles: ["Leadership Transition", "Terminal 2 at Changi Airport"], imageNames: ["SGGCT", "SGChangi2"], descriptions: ["On November 28, 1990, Goh Chok Tong was appointed as Singapore's second Prime Minister, succeeding Lee Kuan Yew. This transition marked a pivotal shift in the nation's political landscape.", "On November 22, 1990, Terminal 2 of Changi Airport commenced operations, expanding the airport's capacity and solidifying its status as a major international aviation hub. "]),
    Decade(id: "2000s", title: "Going Global", subtitles: ["Economic Treaties", "Esplanade Established"], imageNames: ["SGSigning", "SGEsplanade"], descriptions: ["In 2001, Singapore faced an economic recession but responded proactively by signing the United States-Singapore Free Trade Agreement (USSFTA), aiming to bolster trade relations and economic growth.", "The inauguration of this national performing arts center in the Marina Bay area positioned Singapore as a cultural hub in Asia. Its world-class facilities and diverse programming attracted international artists and audiences, elevating Singapore's profile on the global arts scene. "]),
    Decade(id: "2010s", title: "Sports Debut", subtitles: ["Hosting of YOG", "1st Gold Medal"], imageNames: ["SGYOG", "SGGM"], descriptions: ["Singapore hosted the inaugural YOG, marking a significant milestone in its sports history. The event showcased the nation's capability to organize large-scale international sporting competitions and emphasized its commitment to youth development and global engagement.", "Singapore clinched its first Olympic gold medal at the 2016 Rio Olympics in the men's table tennis team event. This achievement was celebrated nationwide, inspiring national pride and highlighting Singapore's growing prominence in international sports."]),
    Decade(id: "2020s", title: "Staying Strong", subtitles: ["COVID-19 Response", "Terminal 2 at Changi Airport"], imageNames: ["SGCB", "SGPope"], descriptions: ["In response to the COVID-19 pandemic, Singapore enacted a \"circuit breaker\" from April to June 2020, implementing strict measures to limit movement and social interactions. This period saw the closure of non-essential businesses and a shift to remote work and online learning. ", "In September 2024, Pope Francis visited Singapore, praising its societal harmony and successful public systems. His visit highlighted Singapore's position as a global city that balances modernity with cultural and religious diversity."]),
    Decade(id: "2030s", title: "The Road Ahead", subtitles: ["2030 Green Plan", "Economic Strategy"], imageNames: ["SG2030", "SGEconomy"], descriptions: ["In response to the COVID-19 pandemic, Singapore enacted a \"circuit breaker\" from April to June 2020, implementing strict measures to limit movement and social interactions. This period saw the closure of non-essential businesses and a shift to remote work and online learning. ", "The Singapore Economy 2030 vision focuses on four key pillars: Trade, Enterprise, Manufacturing and Services, designed to guide Singapore's economic growth and competitiveness in the coming decade. "])
    
    
    ]
